% Project 2 - Question 1

N = 100000;
seed = 123;

H = halton_nodes(1000);

% ####################################################
% Uniform simulations
% ####################################################

N_unif = [1000, 10000, 1000000];

fprintf('\nU(0,1) generated with LCG\n');
fprintf('Theory : mean = %.6f, variance = %.6f\n', 1/2, 1/12);
fprintf('%10s %14s %14s %12s %12s\n', 'N', 'start seed', 'final seed', 'mean', 'variance');

seed_unif = seed;
for i = 1:length(N_unif)
    start_seed = seed_unif;
    [u, seed_unif] = randu01(N_unif(i), start_seed);
    fprintf('%10d %14d %14d %12.6f %12.6f\n', ...
        N_unif(i), start_seed, seed_unif, mean(u), var(u));
end


%% Uniform histograms


[u1, seed_hist] = randu01(1000, seed);
[u2, ~] = randu01(100000, seed_hist);

edges = linspace(0, 1, 11);

figure

subplot(1,2,1)
histogram(u1, edges, 'Normalization', 'pdf')
hold on
plot([0 1], [1 1], 'LineWidth', 2)
title('N = 1000')
xlabel('x')
ylabel('density')
ylim([0 1.2])
box on

subplot(1,2,2)
histogram(u2, edges, 'Normalization', 'pdf')
hold on
plot([0 1], [1 1], 'LineWidth', 2)
title('N = 100000')
xlabel('x')
ylabel('density')
ylim([0 1.2])
box on

% ####################################################
% Normal simulations
% ####################################################


N_norm = [500, 5000, 50000, 500000];

fprintf('\nN(0,1) generated by acceptance-rejection\n');
fprintf('Theory : mean = %.6f, variance = %.6f\n', 0, 1);
fprintf('%10s %12s %12s\n', 'N', 'mean', 'variance');

for i = 1:length(N_norm)
    z = randn_ar(N_norm(i), seed);
    fprintf('%10d %12.6f %12.6f\n', N_norm(i), mean(z), var(z));
end

%% Normal histograms

figure

for i = 1:length(N_norm)
    z = randn_ar(N_norm(i), seed);

    subplot(2,2,i)
    histogram(z, 80, 'Normalization', 'pdf')
    hold on

    xx = linspace(-5, 5, 400);
    plot(xx, exp(-xx.^2/2)/sqrt(2*pi), 'LineWidth', 2)

    title(sprintf('N = %d', N_norm(i)))
    xlabel('x')
    ylabel('density')
    xlim([-5 5])
    box on
end

% ####################################################
% Uniform vs Halton nodes
% ####################################################


N_nodes = 1000;

U = [randu01(N_nodes, seed), randu01(N_nodes, seed + 1)];
H = halton_nodes(N_nodes);

figure

subplot(1,2,1)
plot(U(:,1), U(:,2), '.', 'MarkerSize', 6)
axis square
xlim([0 1])
ylim([0 1])
title('Uniform random nodes')
xlabel('x')
ylabel('y')
box on

subplot(1,2,2)
plot(H(:,1), H(:,2), '.', 'MarkerSize', 6)
axis square
xlim([0 1])
ylim([0 1])
title('Halton nodes')
xlabel('x')
ylabel('y')
box on
